services:
  postgres:
    image: postgres:15
    container_name: GrowUpBro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: GrowUpBro
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/GrowUpBro -user=postgres -password=postgres_pass migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sofyakolodeznikova@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sokol622
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres